# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GCD' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for GCD
  pod 'AFNetworking'
  target 'GCDTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GCDUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
